services:
  - type: web
    name: image-editor-backend
    env: python
    buildCommand: cd ImageEditor/ImageEditorBackend && pip install -r requirements_test.txt
    startCommand: cd ImageEditor/ImageEditorBackend && python server_test.py